---
- name: Apply Redis role
  hosts: server_role_redis_server
  become: true
  vars:
    ansible_user: rocky
  roles:
    - redis  

- name: Apply Frontend role
  hosts: server_role_frontend_server
  become: true
  vars:
    ansible_user: ubuntu
  roles:
    - frontend 